#!/bin/bash

###################################################

# ------------------ 数组定义菜单项 ------------------
Menu_Items=(
	"退出"
	"安装 desktop"
	"安装 gitlab"
	"部署 desktop"
	"部署 gitlab"
	"安装 Docker"
	"安装 Podman"
	"管理 Docker"
	"管理 Podman"
)

# 每个编号对应一个函数（index 对齐 MENU_ITEMS）
Menu_Actions=(
	"exit 0"
	"bash <(curl -sL devopsandy.hdyauto.qzz.io/devops?$(openssl rand -base64 12 | tr -dc 'a-zA-Z0-9' | cut -c1-16)) setup_desktop"
	"bash <(curl -sL devopsandy.hdyauto.qzz.io/devops?$(openssl rand -base64 12 | tr -dc 'a-zA-Z0-9' | cut -c1-16)) setup_gitlab"
	"bash <(curl -sL devopsandy.hdyauto.qzz.io/devops?$(openssl rand -base64 12 | tr -dc 'a-zA-Z0-9' | cut -c1-16)) devops_desktop"
	"bash <(curl -sL devopsandy.hdyauto.qzz.io/devops?$(openssl rand -base64 12 | tr -dc 'a-zA-Z0-9' | cut -c1-16)) devops_gitlab"
	"bash <(curl -sL tool.hdyauto.qzz.io/sys/fun_deps.sh?$(openssl rand -base64 12 | tr -dc 'a-zA-Z0-9' | cut -c1-16)) fundeps_check_install_docker"
	"bash <(curl -sL tool.hdyauto.qzz.io/sys/fun_deps.sh?$(openssl rand -base64 12 | tr -dc 'a-zA-Z0-9' | cut -c1-16)) fundeps_check_install_podman"
	"bash <(curl -sL tool.hdyauto.qzz.io/sys/fun_docker.sh?$(openssl rand -base64 12 | tr -dc 'a-zA-Z0-9' | cut -c1-16)) linux_docker"
	"bash <(curl -sL tool.hdyauto.qzz.io/sys/fun_podman.sh?$(openssl rand -base64 12 | tr -dc 'a-zA-Z0-9' | cut -c1-16)) linux_podman"
)

# ------------------ 数组 → JSON ------------------
Menu_Items_Json=$(printf '%s\n' "${Menu_Items[@]}" | jq -R . | jq -s .)
Menu_Actions_Json=$(printf '%s\n' "${Menu_Actions[@]}" | jq -R . | jq -s .)

# echo "Menu_Items_Json: $Menu_Items_Json"
# echo "Menu_Actions_Json: $Menu_Actions_Json"

remote_main() {
	# ------------------ 调用 setup（强制用 bash） ------------------
	# 下载脚本到变量
	local script_content=$(curl -sSL https://tool.hdyauto.qzz.io/menu/main?$(openssl rand -base64 12 | tr -dc 'a-zA-Z0-9' | cut -c1-16))
	# 写入临时文件
	local tmp_script=$(mktemp)
	echo "$script_content" >"$tmp_script"
	chmod +x "$tmp_script"
	# 正确传参
	"$tmp_script" "$Menu_Items_Json" "$Menu_Actions_Json"

	rm -f "$tmp_script"
}

local_main() {
	# ------------------ 调用 setup（强制用 bash） ------------------
	bash ../devopstool/menu/main "$Menu_Items_Json" "$Menu_Actions_Json"
}

# remote_main
local_main
