#!/bin/bash

###################################################

Token_Sh_Url="$1"       # 获取token脚本连接
GitHub_User="$2"        # GitHub 用户名或组织名
GitHub_Repo_Name="$3"   # 仓库名
GitHub_Path="$4"        # 仓库子目录
GitHub_Repo_Branch="$5" # 分支名，例如 main 或 master
Install_Dir="$6"        # 安装目录

# echo "最终安装目录是：$Install_Dir"

# ------------------ 数组定义菜单项 ------------------
Menu_Items=(
	"退出"
	"（部署） ${GitHub_Path}"
	"安装 Docker"
	"安装 Podman"
	"管理 Docker"
	"管理 Podman"
)

# 每个编号对应一个函数（index 对齐 MENU_ITEMS）
Menu_Actions=(
	"exit 0"
	"bash <(curl -sL devopsandy.hdyauto.qzz.io/devops?$(openssl rand -base64 12 | tr -dc 'a-zA-Z0-9' | cut -c1-16)) remote_deploy "$Token_Sh_Url" "$GitHub_User" "$GitHub_Repo_Name" "$GitHub_Repo_Branch" "$GitHub_Path" "$Install_Dir" "
	"bash <(curl -sL tool.hdyauto.qzz.io/sys/fun_deps.sh?$(openssl rand -base64 12 | tr -dc 'a-zA-Z0-9' | cut -c1-16)) fundeps_check_install_docker"
	"bash <(curl -sL tool.hdyauto.qzz.io/sys/fun_deps.sh?$(openssl rand -base64 12 | tr -dc 'a-zA-Z0-9' | cut -c1-16)) fundeps_check_install_podman"
	"bash <(curl -sL tool.hdyauto.qzz.io/sys/fun_docker.sh?$(openssl rand -base64 12 | tr -dc 'a-zA-Z0-9' | cut -c1-16)) linux_docker"
	"bash <(curl -sL tool.hdyauto.qzz.io/sys/fun_podman.sh?$(openssl rand -base64 12 | tr -dc 'a-zA-Z0-9' | cut -c1-16)) linux_podman"
)

# ------------------ 数组 → JSON ------------------
Menu_Items_Json=$(printf '%s\n' "${Menu_Items[@]}" | jq -R . | jq -s .)
Menu_Actions_Json=$(printf '%s\n' "${Menu_Actions[@]}" | jq -R . | jq -s .)

# ------------------ 调用 setup（强制用 bash） ------------------
# 下载脚本到变量
local script_content=$(curl -sSL https://tool.hdyauto.qzz.io/menu/setup?$(openssl rand -base64 12 | tr -dc 'a-zA-Z0-9' | cut -c1-16))
# 写入临时文件
local tmp_script=$(mktemp)
# echo "$script_content" >"$tmp_script"
chmod +x "$tmp_script"
# 正确传参
"$tmp_script" \
	"$Token_Sh_Url" \
	"$GitHub_User" \
	"$GitHub_Repo_Name" \
	"$GitHub_Path" \
	"$GitHub_Repo_Branch" \
	"$Install_Dir" \
	"$Menu_Items_Json" \
	"$Menu_Actions_Json"

rm -f "$tmp_script"

# # ------------------ 调用 setup（强制用 bash） ------------------
# bash ../devopstool/menu/setup \
# 	"$Token_Sh_Url" \
# 	"$GitHub_User" \
# 	"$GitHub_Repo_Name" \
# 	"$GitHub_Path" \
# 	"$GitHub_Repo_Branch" \
# 	"$Install_Dir" \
# 	"$Menu_Items_Json" \
# 	"$Menu_Actions_Json"
