#!/bin/bash

###################################################

echo_content() {
	local tmp_color="$1" # 颜色
	local tmp_text="$2"  #  文本
	local tmp_opt="$3"   # 第三个参数用于传 -n

	local tmp_echo_type="echo -e"
	[ "$tmp_opt" = "-n" ] && tmp_echo_type="echo -en"

	case "$tmp_color" in
	"red") $tmp_echo_type "\033[31m${tmp_text}\033[0m" ;;
	"green") $tmp_echo_type "\033[32m${tmp_text}\033[0m" ;;
	"yellow") $tmp_echo_type "\033[33m${tmp_text}\033[0m" ;;
	"blue") $tmp_echo_type "\033[34m${tmp_text}\033[0m" ;;
	"purple") $tmp_echo_type "\033[35m${tmp_text}\033[0m" ;;
	"skyBlue") $tmp_echo_type "\033[36m${tmp_text}\033[0m" ;;
	"white") $tmp_echo_type "\033[37m${tmp_text}\033[0m" ;;
	esac
}

# ------------------ 数组定义菜单项 ------------------
Memu_Items=(
	"退出"
	"安装 devops-desktop"
	"部署 devops-desktop"
	"安装 devops-gitlab"
	"部署 devops-gitlab"
	"Postman工具"	
)

Rand_Str=$(openssl rand -base64 12 | tr -dc 'a-zA-Z0-9' | cut -c1-16)

# 每个编号对应一个函数（index 对齐 MENU_ITEMS）
Mennu_Actions=(
	"exit 0"
	"bash <(curl -sL devopsandy.hdyauto.qzz.io/devops/setup_desktop.sh?$Rand_Str)"
	"bash <(curl -sL devopsandy.hdyauto.qzz.io/devops/devops_desktop.sh?$Rand_Str)"
	"bash <(curl -sL devopsandy.hdyauto.qzz.io/devops/setup_gitlab.sh?$Rand_Str)"
	"bash <(curl -sL devopsandy.hdyauto.qzz.io/devops/devops_gitlab.sh?$Rand_Str)"
	"bash <(curl -sL tool.hdyauto.qzz.io/sys/fun_podman.sh?$Rand_Str) linux_podman"
)

main() {

	# ------------------ 主循环 ------------------
	while true; do
		clear
		echo_content "skyBlue" "============================"
		echo_content "red" " 安装菜单 "
		echo_content "skyBlue" "============================"
		for i in "${!Memu_Items[@]}"; do
			((i == 0)) && continue
			echo_content "white" " $((i))) " -n
			echo_content "green" "${Memu_Items[$i]}"
		done
		echo ""
		echo_content "white" " 0) " -n
		echo_content "green" "${Memu_Items[0]}"
		echo_content "skyBlue" "============================"
		echo_content "skyBlue" "请选择操作: " -n
		read -r choice

		# 转为下标（减 1）
		if [[ "$choice" =~ ^[0-9]+$ ]] && [ "$choice" -ge 0 ] && [ "$choice" -le "${#Memu_Items[@]}" ]; then
			index=$((choice))
			# echo "-------- $index"
			# echo "${Memu_Items[$index]}"
			echo_content "skyBlue" ">> 执行: ${Memu_Items[$index]}"
			eval "${Mennu_Actions[$index]}"
		else
			echo_content "skyBlue" "无效选择。"
		fi

		echo_content "yellow" "按任意键继续..." -n
		read -n 1 -s -r
		echo # 输入后换行（可选）
	done
}

# ======= 安装默认工具 =======
check_install_deps

# ======= 启动程序 =======
main
